name: Testing site config
type: profile
description: 'Minimal profile for testing with default site config.'
# version: VERSION
core: 8.x
hidden: true

# Information added by Drupal.org packaging script on 2020-11-26
version: '8.8.12'
project: 'drupal'
datestamp: 1606360921
